# Generated by Django 2.1.7 on 2019-08-29 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantes', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True)),
                ('texto', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.Chat')),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_de', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_para', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
