# Generated by Django 2.1.7 on 2019-08-29 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_amistad_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amistad',
            options={'verbose_name_plural': 'amistades'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'solicitudes'},
        ),
        migrations.RemoveField(
            model_name='amistad',
            name='amigos',
        ),
        migrations.AddField(
            model_name='amistad',
            name='amigoPropone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ami1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amistad',
            name='amigoPropuesto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ami2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
