# Generated by Django 2.1.7 on 2019-08-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190829_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
