# Generated by Django 2.1.7 on 2019-08-29 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('empleado', models.CharField(max_length=50)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('turno_desde', models.DateTimeField()),
                ('turno_hasta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('Cancha de 11', '11'), ('Cancha de 7 abierta', '7ABIERTA'), ('Cancha de 5 abierta', '5ABIERTA'), ('Cancha de 7 techada', '7TECHADA'), ('Cancha de 5 techada', '5TECHADA')], default='Cancha de 5 techada', max_length=20)),
                ('tiene_vestuario', models.BooleanField(default=False)),
                ('tiene_iluminacion', models.BooleanField(default=False)),
                ('tiene_cesped_sintetico', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='alquiler',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='canchas.Cancha'),
        ),
    ]
