# Generated by Django 2.1.7 on 2019-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_auto_20190829_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
